export const SettingActionTypes = {
    SET_CURRENT_SETTING: 'SET_CURRENT_SETTING',
    SET_SETTING_UPLOAD_PROGRESS: 'SET_SETTING_UPLOAD_PROGRESS',
    SET_ROUTE_MOUNT_STATUS: 'SET_ROUTE_MOUNT_STATUS',
}